---
title: "Data-based essay"
date: "2023-02-07"
---

Use data from the [OECD](https://data.oecd.org/), [World Bank](https://data.worldbank.org/), [Varieties of Democracy (V-Dem) project](https://www.v-dem.net/), or [Quality of Governance (QoG) project](https://www.gu.se/en/quality-government/qog-data) to compare some aspect of the public sector across five countries. These data sources include information about public sector labor force participation, gender proportions in bureaucracy, civil society openness and restrictions, human resource management policies, and a host of other public policy and management issues.

You will select **one public sector issue** and **five countries** and collect the relevant data on the issue for **at least the past ten years** (if available). You will then summarize and visualize trends in the data and draw conclusions about the issue in these countries. You will conclude with a discussion of what the trends in these five countries might mean for the public sector in other countries.

Broadly speaking, your essay should include:

- A justification and summary of your chosen issue area and data source—why does it matter, and why should we care about what it looks like around the world?
- A justification for your five chosen countries—why these? are they representative of general regime types or regions?
- A graph and/or table showing changes in your chosen measure over the past decade
- A discussion and speculation of why the measure has changed over time—try connecting changes to political changes, civil conflicts, or economic developments
- A discussion of what these trends might mean for the public sector more globally

You will submit this essay via iCollege.

I will grade this with a rubric that I will provide later.
