---
title: "Mini presentation and discussion leading"
---

You will be responsible for preparing a short presentation on the readings and leading the discussion for one week. During the first day of class, I will provide a spreadsheet where you will select the week you want to be responsible for.

When it is your turn to present and lead the discussion, you should do the following:

### Presentation

For your presentation, you should create either (1) a PowerPoint slideshow or (2) a summary handout (if you do this, e-mail it to me so I can print out copies for the class). 

Your 12-minute presentation should include the following:

- A summary of the main arguments of the assigned readings
- An exploration of how the readings explain and potentially solve practical public management/administration issues
- An explanation of the practical implications of the readings and key takeaways for management and policy practices
- Several critiques of the readings 
- A discussion of things you did not understand


### Discussion leading

After your presentation, you'll help lead a 10-minute discussion with the entire. **Don't worry!**—this does not mean that you need to teach the class! Create a list of 4–6 questions that your classmates can discuss. These should be broad and more abstract (i.e. don't ask things like "What did Author X say on p. 113?"). 

Here are some good sample questions that you can adapt:

- How can you relate the concepts and ideas in the readings to real world issues in policy and management?
- What are the practical implications of the readings?
- What are some issues with or critiques of the readings' research design and methods?
- What are some suggestions for further research questions?


### Grading

I will grade this using a check system similar to the reading report:

- ✔+: (*46 points (115%) in gradebook*) Presentation shows phenomenal thought and engagement with the course content. I will not assign these often.
- ✔: (*40 points (100%) in gradebook*) Presentation is thoughtful, well-done, and shows engagement with the course content. This is the expected level of performance.
- ✔−: (*20 points (50%) in gradebook*) Presentation is too short, too basic, and/or only cursorily engages with the course content. I will hopefully not assign these often.
