---
title: "Reading report"
toc: false
---

You will get the most out of this seminar if you (1) attend regularly, (2) engage with the readings, and (3) write thoughtfully.

You should read all the assigned articles each week using [the grad school reading skills we read about and talked about on the first day of class](/class/01-class.qmd). Keep notes of the main arguments, methods, surprises, and shortcomings in each reading, think about how the readings connect to each other, and consider how the readings apply to real-world governance.

Before class on Tuesdays, you need to write a reading report about what you've read. This report is designed to (1) allow you to engage with the assigned readings, (3) help you practice high quality academic writing, and (3) help you be prepared for in-class discussions of the readings.

Reading reports are due by 11:59 PM on the day before class (e.g., the reading report for January 17's seminar is due at 11:59 PM on January 16).

[**You must follow the report template below.**](#report-template)

I will grade these based on completion using a check system:

- ✔+: (*23 points (115%) in gradebook*) Report shows phenomenal thought and engagement with the course content. I will not assign these often.
- ✔: (*20 points (100%) in gradebook*) Report is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
- ✔−: (*10 points (50%) in gradebook*) Report is hastily composed, too short, does not follow the template, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I'm not counting the exact number of words you're writing, and I'm not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. I'm looking for thoughtful engagement. That's all. Do good work and you'll get a ✓.

You will submit these reports via iCollege.


## Report template

You must follow this template for your reading report. 

Use headings in Word or Google Docs or whatever program you write in. Cite your sources appropriately and include a bibliography at the end of the report (you can do this automatically if you use [Zotero!](https://www.zotero.org/)).

::: {.callout-tip}

## Report template

### Summary of readings

Write 1 paragraph *for each* reading. Make sure you (1) summarize its main points, (2) praise it for doing something well, (3) and perhaps criticize it for something it missed or did poorly or didn't convince you of.

##### Author(s), "Title of first reading"

Blah blah blah.

##### Author(s), "Title of second reading"

Blah blah blah

##### And so on…

Blah blah blah


### Synthesis of readings

##### Connections and overall themes

Write 1–2 paragraphs about the connections that you found between the readings. What did the authors agree with? What did they disagree with? Are there contradictory findings? ([Watch this](https://www.youtube.com/watch?v=R_rnkM7jvlY) for a good definition and overview of what synthesis is and how it's different from summarizing.)

##### Surprises

Write 1 paragraph answering **one** of these questions:

- What surprised/delighted/confused/annoyed you the most in the readings? Why?
- Which previous readings do these remind you of? Why?
- Which 2–3 passages do you most want to hear classmates react to? Why?


### References

This will be generated automatically if you use Zotero.
:::
