project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Explore how the public and nonprofit sectors work around the world and learn how political institutions shape government and civil society"

website:
  title: "Comparative Public Administration"
  site-url: "https://compasp23.classes.andrewheiss.com"

  favicon: "/files/favicon-512.png"

  twitter-card:
    image: "/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#1E466E"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Classes"
        file: class/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd

  sidebar:
    - title: "Classes"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - class/index.qmd
        - section: "Classes"
          contents:
            - section: "1–3: Foundations of public management and governance"
              contents:
                - text: "1: Introduction to public administration and management"
                  file: class/01-class.qmd
                - text: "2: Rediscovery of bureaucracy and good governance"
                  file: class/02-class.qmd
                - text: "3: Quality of government and governance outcomes"
                  file: class/03-class.qmd
            - section: "4–9: Comparative bureaucracy and civil society"
              contents:
                - text: "4: Bureaucracy and governance outcomes"
                  file: class/04-class.qmd
                - text: "5: Bureaucracy and bureaucratic behavior"
                  file: class/05-class.qmd
                - text: "6: Civil society and good governnace"
                  file: class/06-class.qmd
                - text: "7: Civil society across countries"
                  file: class/07-class.qmd
                - text: "8: Representative bureaucracy and philanthropy"
                  file: class/08-class.qmd
                - text: "9: The OECD"
                  file: class/09-class.qmd
            - section: "10–13: Regional deep dives"
              contents:
                - text: "10: Latin America"
                  file: class/10-class.qmd
                - text: "11: Africa"
                  file: class/11-class.qmd
                - text: "12: Middle East and North Africa"
                  file: class/12-class.qmd
                - text: "13: Asia"
                  file: class/13-class.qmd
            - section: "14: Conclusion"
              contents:
                - text: "14: Conclusions"
                  file: class/14-class.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Individual assignments"
          contents:
            - assignment/pre-class-check-in.qmd
            - assignment/01-why-nonprofits.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
