---
title: "Rediscovery of bureaucracy and good governance"
date: "2023-01-17"
---

## Readings

- {{< fa brands youtube >}}&ensp;[Summary vs. synthesis](https://www.youtube.com/watch?v=R_rnkM7jvlY)

- {{< fa file-pdf >}}&ensp;(***Skim***) [@Olsen:2005]

- {{< fa file-pdf >}}&ensp;[@EvansRauch:1999]

- {{< fa file-pdf >}}&ensp;[@Fukuyama:2013]

- {{< fa file-pdf >}}&ensp;[@HolmbergRothsteinNasiritousi:2009]


## Plan for the day

- **More tips and tricks for reading, note-taking, and writing**

  - [Zotero](https://www.zotero.org/) + [Zotero Connector](https://www.zotero.org/download/connectors) + [GSU's Zotero guide](https://research.library.gsu.edu/zotero)
  - [Class Zotero group library](https://www.zotero.org/groups/compasp23)

  - Taking and storing notes:
    - [Zotero](https://www.zotero.org/)
    - [Obsidian](https://obsidian.md/)
    - [Notion](https://www.notion.so/)
    - [OneNote](https://www.onenote.com/?public=1)
    - [Evernote](https://evernote.com/)
    
  - [Zotero in Word](https://www.zotero.org/support/word_processor_plugin_usage) + [Zotero in Google Docs](https://www.zotero.org/support/google_docs) + Zotero [in RStudio](https://posit.co/blog/rstudio-1-4-preview-citations/) or [with Markdown in general](https://www.andrewheiss.com/blog/2023/01/08/bibdesk-to-zotero-pandoc/#example-workflow-with-quarto-r-markdown-pandoc)
  
  - [Summary vs. synthesis](https://www.youtube.com/watch?v=R_rnkM7jvlY) + [The Synthesis Test](https://www.youtube.com/watch?v=R_rnkM7jvlY&t=241s)

- **How to discuss an article in a seminar**

  - Who wrote the article? What’s their background?
  - General summary of the article
  - Strengths
  - Weaknesses
  - How does it connect to other readings?
  - How does it connect to the broader course themes?
  - How does it connect to current events?
  - What does it add to our Global Bureaucracy Toolkit^™^?

- **Why does bureaucracy matter and is it going anywhere?**

  - [@MeierHill:2005]
  - [@Olsen:2005]

- **Defining and measuring governance**

  - How can we measure abstract concepts like "governance?"
  - [@EvansRauch:1999]
  - [@Fukuyama:2013]
  - [@HolmbergRothsteinNasiritousi:2009]
