---
title: "Institutions"
date: "2023-01-24"
---

## Readings

- {{< fa file-pdf >}}&ensp;Chapter 1 in [@North:1990]

- {{< fa file-pdf >}}&ensp;Chapters 1, 11, and 12 in [@AcemogluRobinson:2012]

- {{< fa file-pdf >}}&ensp;[@DiMaggioPowell:1983]

- {{< fa file-pdf >}}&ensp;[@Alston:2017]

### Really good but optional

- {{< fa file-pdf >}}&ensp;Chapter 2 in [@Ostrom:1990]


## Article discussion reminder

**How to discuss an article in a seminar**

- Who wrote the article? What’s their background?
- General summary of the article
- Strengths
- Weaknesses
- How does it connect to other readings?
- How does it connect to the broader course themes?
- How does it connect to current events?
- What does it add to our Global Bureaucracy Toolkit^™^?


## Plan for the day

- **Mini-presentation on governance**

- **Mini-presentation and discussion on institutions**

- **Overview of different conceptions of institutions**

- **Institutions and comparative public administration**

  - [@North:1990]
  - [@AcemogluRobinson:2012]
  - [@DiMaggioPowell:1983]
  - [@Alston:2017]
